version: 2
jobs:
  build:
    working_directory: ~/workspace/dash_visual
    docker:
      - image: circleci/python:3.6-stretch-browsers
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run: mkdir test-results && sudo chown -R circleci:circleci test-results
      - run:
          name: Prepare run appication
          command: |
            cd dash_visual/src
            pip install --user -r requirements.txt 
            mv ../tests/e2e/assets/result_all.csv .
            mv ../tests/e2e/assets/result_kanto.csv .
            mv ../tests/e2e/assets/result_timeserias_all.csv .
      - run:
          name: Run application
          command: cd dash_visual/src && python application.py
          background: true
      - run:
          name: Prepare e2e test
          command: |
            cd dash_visual/tests/e2e
            pip install --user -r requirements-test.txt
      - run:
          name: Run e2e test
          command: cd dash_visual/tests/e2e && pytest e2e.py
      - store_artifacts:
          path: tests/e2e/screenshots
