branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: map-view
  branch: null
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
